name: Goveralls

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Run goveralls
      run: $HOME/go/bin/goveralls -service=github-actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
